#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { checkoutExactCommit } from './bootstrap-upstream.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const suiteRoot = path.join(root, '.skin-suite');
const generatedRoot = path.join(suiteRoot, 'generated');
const minervaRoot = path.join(suiteRoot, 'minerva');
const statePath = path.join(suiteRoot, 'state.json');
const loaderPath = path.join(generatedRoot, 'variant-loaders.js');
const suiteLockPath = path.join(root, 'SUITE-LOCK.json');
const gitExecutable = process.platform === 'win32' ? 'git.exe' : 'git';

function fail(message) {
  throw new Error(message);
}

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function writeFileAtomic(file, value) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const temporary = `${file}.${process.pid}.tmp`;
  fs.writeFileSync(temporary, value);
  if (fs.existsSync(file)) fs.rmSync(file, { force: true });
  fs.renameSync(temporary, file);
}

function writeJsonAtomic(file, value) {
  writeFileAtomic(file, `${JSON.stringify(value, null, 2)}\n`);
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: options.cwd || root,
    stdio: options.capture ? ['ignore', 'pipe', 'pipe'] : 'inherit',
    encoding: 'utf8',
    env: { ...process.env, ...(options.env || {}) },
    windowsHide: true
  });
  if (result.error) throw result.error;
  if (result.status !== 0) {
    const detail = options.capture ? `\n${result.stderr || result.stdout || ''}` : '';
    fail(`${command} ${args.join(' ')} failed with status ${result.status}.${detail}`);
  }
  return options.capture ? String(result.stdout || '').trim() : '';
}

function resolveNpmCli() {
  const candidates = [
    process.env.npm_execpath,
    path.join(path.dirname(process.execPath), 'node_modules', 'npm', 'bin', 'npm-cli.js'),
    path.join(path.dirname(path.dirname(process.execPath)), 'lib', 'node_modules', 'npm', 'bin', 'npm-cli.js')
  ].filter(Boolean);
  return candidates.find((candidate) => fs.existsSync(candidate) && fs.statSync(candidate).isFile()) || null;
}

function runNpm(cwd, args) {
  const npmCli = resolveNpmCli();
  if (npmCli) return run(process.execPath, [npmCli, ...args], { cwd });
  if (process.platform === 'win32') {
    return run(process.env.ComSpec || 'cmd.exe', ['/d', '/s', '/c', 'npm', ...args], { cwd });
  }
  return run('npm', args, { cwd });
}

function normalizeAbsolute(value) {
  return path.resolve(value).replaceAll('\\', '/');
}

function assertManagedSuitePath(target) {
  const resolved = path.resolve(target);
  if (resolved !== suiteRoot && !resolved.startsWith(`${suiteRoot}${path.sep}`)) {
    fail(`Managed suite path escapes .skin-suite: ${target}`);
  }
  return resolved;
}

export function parseSuiteArgs(argv) {
  const parsed = {
    vectorOnly: false,
    clean: false,
    upstreamArgs: []
  };
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === '--vector-only') {
      parsed.vectorOnly = true;
    } else if (arg === '--clean' || arg === '--refresh') {
      if (arg === '--clean') parsed.clean = true;
      parsed.upstreamArgs.push(arg);
    } else if (arg === '--release') {
      const release = argv[index + 1] || '';
      parsed.upstreamArgs.push(arg, release);
      index += 1;
    } else if (arg.startsWith('--release=')) {
      parsed.upstreamArgs.push(arg);
    } else {
      fail(`Unknown bootstrap option: ${arg}`);
    }
  }
  return parsed;
}

export function renderVariantLoader(mode, minervaEntry = 'layout.vue') {
  if (mode !== 'vector-only' && mode !== 'vector-minerva') fail(`Unsupported suite mode: ${mode}`);
  if (!/^[A-Za-z0-9_./-]+\.vue$/.test(minervaEntry) || minervaEntry.includes('..')) {
    fail(`Invalid Minerva suite entry: ${minervaEntry}`);
  }
  const minervaLoader = mode === 'vector-minerva'
    ? `() => import('../minerva/${minervaEntry}')`
    : 'null';
  return [
    '// Generated by tools/vector-suite.mjs. Do not edit.',
    `export const suiteMode = '${mode}';`,
    "export const loadVectorVariant = () => import('../../components/VectorVariantLayout.vue');",
    `export const loadMinervaVariant = ${minervaLoader};`,
    ''
  ].join('\n');
}

function activateSuiteMode(mode, lock = readJson(suiteLockPath)) {
  writeFileAtomic(loaderPath, renderVariantLoader(mode, lock.minerva.entry));
  writeJsonAtomic(statePath, {
    schema: 1,
    mode,
    minervaCommit: mode === 'vector-minerva' ? lock.minerva.commit : null,
    minervaEntry: mode === 'vector-minerva' ? lock.minerva.entry : null
  });
}

export function ensureSuiteLoader() {
  if (fs.existsSync(loaderPath) && fs.existsSync(statePath)) return;
  activateSuiteMode('vector-only');
}

function removeManagedSuite() {
  const target = assertManagedSuitePath(suiteRoot);
  fs.rmSync(target, { recursive: true, force: true });
}

function localMinervaSource(commit) {
  const candidate = path.resolve(root, '..', 'minerva');
  if (!fs.existsSync(path.join(candidate, 'package.json'))) return null;
  const result = spawnSync(gitExecutable, [
    '-c', `safe.directory=${normalizeAbsolute(candidate)}`,
    '-C', candidate,
    'cat-file', '-e', `${commit}^{commit}`
  ], {
    cwd: root,
    stdio: ['ignore', 'ignore', 'ignore'],
    windowsHide: true
  });
  return result.status === 0 ? candidate : null;
}

async function prepareMinerva(lock, clean) {
  if (clean && fs.existsSync(minervaRoot)) {
    fs.rmSync(assertManagedSuitePath(minervaRoot), { recursive: true, force: true });
  }
  const localSource = localMinervaSource(lock.minerva.commit);
  const repositoryUrl = localSource || `https://github.com/${lock.minerva.repository}.git`;
  console.log(`[suite] Minerva source: ${localSource ? `local ${localSource}` : lock.minerva.repository}`);
  await checkoutExactCommit({
    checkout: minervaRoot,
    url: repositoryUrl,
    commit: lock.minerva.commit,
    sparseCheckout: false,
    label: 'thetree-skin-minerva',
    preservePaths: [
      '.build-tools',
      '.upstream',
      'node_modules',
      'vendor',
      'images',
      'css/vendor',
      'lib/generated',
      'components'
    ]
  });

  const packageMetadata = readJson(path.join(minervaRoot, 'package.json'));
  if (packageMetadata.name !== 'thetree-skin-minerva') fail(`Unexpected Minerva package name: ${packageMetadata.name}`);
  if (packageMetadata.version !== lock.minerva.packageVersion) {
    fail(`Minerva package version mismatch: expected ${lock.minerva.packageVersion}, got ${packageMetadata.version}`);
  }
  if (!fs.existsSync(path.join(minervaRoot, lock.minerva.entry))) {
    fail(`Locked Minerva integration entry is missing: ${lock.minerva.entry}`);
  }

  const bootstrapArgs = ['run', 'bootstrap'];
  if (clean) bootstrapArgs.push('--', '--clean');
  runNpm(minervaRoot, bootstrapArgs);

  const vectorRelease = readJson(path.join(root, 'UPSTREAM-LOCK.json')).mediaWikiRelease;
  const minervaRelease = readJson(path.join(minervaRoot, 'UPSTREAM-LOCK.json')).mediaWikiRelease;
  if (vectorRelease !== minervaRelease || vectorRelease !== lock.minerva.mediaWikiRelease) {
    fail(`Vector/Minerva MediaWiki release mismatch: vector=${vectorRelease}, minerva=${minervaRelease}, suite=${lock.minerva.mediaWikiRelease}`);
  }
}

async function main() {
  const options = parseSuiteArgs(process.argv.slice(2));
  const lock = readJson(suiteLockPath);
  if (lock.schema !== 1 || lock.mode !== 'vector-minerva') fail('Unsupported SUITE-LOCK.json contract.');

  if (options.clean) removeManagedSuite();
  activateSuiteMode('vector-only', lock);
  run(process.execPath, [path.join(root, 'tools', 'bootstrap-upstream.mjs'), ...options.upstreamArgs]);

  if (options.vectorOnly) {
    if (fs.existsSync(minervaRoot)) fs.rmSync(assertManagedSuitePath(minervaRoot), { recursive: true, force: true });
    activateSuiteMode('vector-only', lock);
    run(process.execPath, [path.join(root, 'tools', 'vector-suite-contract-test.mjs')]);
    console.log('Vector-only bootstrap complete.');
    return;
  }

  await prepareMinerva(lock, options.clean);
  activateSuiteMode('vector-minerva', lock);
  run(process.execPath, [path.join(root, 'tools', 'vector-suite-contract-test.mjs')]);
  console.log(`Vector + Minerva suite bootstrap complete at Minerva ${lock.minerva.commit}.`);
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.stack || error.message : String(error));
    process.exit(1);
  });
}
